/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing
}

group = "top.natsuu"
version = rootProject.file(".maa-framework-version").readText().trim().removePrefix("v")

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    api(libs.jna)
    api(libs.jackson.databind)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        artifactId = "maa-framework-java"
        from(components["java"])

        pom {
            name.set("MaaFramework Java Binding")
            description.set("JNA-based Java bindings for MaaFramework")
            url.set("https://github.com/Craun718/maa-framework-java")
            licenses {
                license {
                    name.set("MIT")
                    url.set("https://opensource.org/licenses/MIT")
                }
            }
            developers {
                developer {
                    id.set("craun718")
                    name.set("Sander")
                }
            }
            scm {
                connection.set("scm:git:git://github.com/Craun718/maa-framework-java.git")
                developerConnection.set("scm:git:ssh://git@github.com/Craun718/maa-framework-java.git")
                url.set("https://github.com/Craun718/maa-framework-java")
            }
        }
    }
}

signing {
    val signingKeyId = providers.gradleProperty("signing.keyId")
        .orElse(providers.environmentVariable("CENTRAL_PORTAL_SIGNING_KEY_ID"))
        .map(String::trim)
        .filter { it.isNotEmpty() }
    val signingPassword = providers.gradleProperty("signing.password")
        .orElse(providers.environmentVariable("CENTRAL_PORTAL_SIGNING_PASSWORD"))
    val signingKey = providers.gradleProperty("signing.key")
        .orElse(providers.environmentVariable("CENTRAL_PORTAL_SIGNING_KEY"))
        .map(String::trim)
        .filter { it.isNotEmpty() }
    val signingSecretKeyRingFile = providers.gradleProperty("signing.secretKeyRingFile")

    if (signingKey.isPresent) {
        useInMemoryPgpKeys(signingKeyId.orNull, signingKey.get(), signingPassword.orNull)
    } else if (signingSecretKeyRingFile.isPresent) {
        useGpgCmd()
    }

    val shouldSign = providers.gradleProperty("signing.enabled").map { it.toBoolean() }.orElse(false)
    isRequired = shouldSign.get()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    val libDir = providers.gradleProperty("maafw.libDir")
    val sourceDir = providers.gradleProperty("maafw.maaFrameworkSource")
    val sinkLog = providers.gradleProperty("maafw.sinkLog")
    if (libDir.isPresent) {
        systemProperty("maafw.libDir", libDir.get())
    }
    if (sourceDir.isPresent) {
        systemProperty("maafw.maaFrameworkSource", sourceDir.get())
    }
    if (sinkLog.isPresent) {
        systemProperty("maafw.sinkLog", sinkLog.get())
    }
}
